### ISSUE TITLE
Problems with windows build

### ISSUE THREAD

**Issue by fgregg** [dirko/pyhacrf#25]
Hi @dirko,

There's some problems building for windows. You can see it here:

https://ci.appveyor.com/project/fgregg/dedupe/build/1.0.210#L117

**Comment by fgregg** [comment]
I think this is what you need to do: http://docs.scipy.org/doc/numpy-1.10.0/reference/c-api.coremath.html#linking-against-the-core-math-library-in-an-extension

**Comment by dirko** [comment]
Hi @fgregg ,
I'll try to reproduce - do you get the same in your Windows environment?

**Comment by fgregg** [comment]
Thanks! I don't have a window's environment, unfortunately.

**Comment by fgregg** [comment]
This problem, ultimately, didn't have anything to do with pyhacrf. Sorry.

**Comment by dirko** [comment]
Glad to hear!
