### ISSUE TITLE
Binary wheels?

### ISSUE THREAD

**Issue by fgregg** [dirko/pyhacrf#26]
Hi @dirko,

For dedupe, I've setup some scripts to automatically build [binary wheels](https://wheel.readthedocs.org/en/latest/) for OS X and windows for many of the dependencies. This makes it a _lot_ easier for people to use these libraries.

ex: https://github.com/datamade/affinegap/blob/master/.travis.yml
https://github.com/datamade/affinegap/blob/master/appveyor.yml

When you push a tag to github, it automatically builds these wheels and deploys them to github.

Would you be interested in me writing these scripts for `pyhacrf`?

**Comment by dirko** [comment]
Hi @fgregg!

I'll definitely be interested - let me know how I can help (I should have some time over this weekend)

**Comment by fgregg** [comment]
I'll make some pull requests that should get you 90% of the way there!

**Comment by fgregg** [comment]
Now working (would be easy to adapt for this repo) https://travis-ci.org/datamade/pyhacrf
https://ci.appveyor.com/project/fgregg/pyhacrf

https://pypi.python.org/pypi/pyhacrf-datamade
