### ISSUE TITLE
Dynamic program without an edgelist.

### ISSUE THREAD

**Issue by fgregg** [dirko/pyhacrf#29]
With the speedups possible from using an approximate log and exp #27, pyhacrf is very close to usable for applications that make millions of comparisons. However, there is is still a lot of overhead from calculating the edges.

For models where the only transition is between adjacent positions in the string1, string2 matrix, we could avoid calculating the edgelist altogether. I think I'll write up model that does just that.

**Comment by dirko** [comment]
:+1: Thanks!

**Comment by fgregg** [comment]
Fixed in https://github.com/datamade/pyhacrf/commit/2b55973edc6e983f10067735b46e75551a2009a3
