### ISSUE TITLE
Single character string matches

### ISSUE THREAD

**Issue by fgregg** [dirko/pyhacrf#9]
How do you indicate that two one character strings match, since the transition matrix starts at the first character? 

In typical string distance dynamic programs we start before the transition matrix starts before the first character so we can indicate matches.

**Comment by dirko** [comment]
Yes this implementation differs in that regard. If there are two classes the the lattice will be:

```
class 0         class 1
A   .              A  .

    B                 B
```

If the characters A=B match then the `match` feature on this single lattice position will fire and you'll get the expected result, for example that class 0 will be less likely than class 1.

I think the current implementation is general enough that you can get the same effect as the more standard way by setting up a more complicated state machine with a dedicated start state that can only transition diagonally (1, 1), and by always prepending strings with some start character.

**Comment by fgregg** [comment]
Got it! Thanks.
